beartype/beartype

doc/requirements.txt
doc/source/404.rst
doc/source/conf.py

From #8: Here's a suggestion for RTD+Sphinx configuration.
RTD can be set up without any further configuration files from their UI. Would you still like it to use the YAML? I think it's simply a matter of preference.
When creating a RTD site, one can import from their GitHub account, or manually set up a site. It could be better if you create the site, and then if I'm needed, I can be added to the project. I'm not sure if manual creation has some drawbacks, but I'd prefer not to test it just to see that it does 😅

Documentation configuration

---

README.rst
doc/source/index.rst

From #8: This PR adds logos to the mix!
Three things should be taken into account / resolved.
- The slogan is kinda awkward just beneath the logo, but that could be just me.
- On RTD, having the logo as a heading produces a site with no title. Granted, *Beartype* appears right after, but I wish there was a way to either include the title or remove the hyphen.
- Now the links point to RTD. Maybe you'd like PyPI instead, or GitHub -> RTD and RTD -> PyPI? The possibilities are endless and equally confusing for users repeatedly clicking the banner 😄

Add logo to README and documentation

---

beartype/_util/cache/pool/utilcachepool.py
beartype/roar.py
beartype_test/unit/a00_util/cache/pool/test_utilcachepool.py

The implementation of KeyPool does not check whether the object passed
to `release()` has passed through `acquire()`. Reference the issue at
the bottom of the commit for additional details.
Breakdown of changes:
- Add new exception "_BeartypeUtilKeyPoolException"
- Implement validation on `release()` which now throws the above
exception if passed an object either already released or not
registered via `acquire()`
- Add test cases confirming the above implementation
Resolves: #13

feat: Track Object's acquisition state in KeyPool

---

beartype/_util/utilcallable.py
beartype/cave.py
beartype_test/a00_unit/a00_util/test_utilcallable.py

Implements the basic grab of filename or placeholder for any callable
object. Reference the issue at the bottom for additional details.
Types were combined in cave.py both for  current and future use.
Breakdown of Changes:
- Add a new exception `_BeartypeUtilCallableException`
- Add a tuple to cave.py off all callable CType named `CallableCtypes`
- Implement `get_callable_filename_or_placeholder`
- Add test for extent of current implementation
Reference: #18

feat: Add base for `utilcallable`

---

beartype/_util/text/utiltextmunge.py
beartype/_util/text/utiltextrepr.py
beartype_test/a00_unit/a00_util/text/test_utiltextmunge.py

This PR looks to resolve [the issue of not having unit tests for  `utiltextmunge.py`](https://github.com/beartype/beartype/blob/main/beartype/_util/text/utiltextmunge.py#L67). I  ended up adding basic unit tests for all functions in `utiltextmunge.py`.
I'd specifically like to draw your attention to [this section](https://github.com/beartype/beartype/compare/main...Heliotrop3:dev?expand=1#diff-233a4c754947e50477198537f33a68cbafb4e5265ba2db0503bb48a4764a48b9R49-R56). As per the comment, I am unsure whether this is a worth-while test. Given it's a 1:1 copy of the function's return statement it's given to fail should the function ever change. That being said, it's unsurprisingly also the most compact way of producing the expected result... 
Slipped into this PR is also the resolution of a …

test: Add test cases for `utiltextmunge`

---

README.rst

Depends on ~beartype/beartype-assets#4~ _[merged](https://github.com/beartype/beartype-assets/pull/4#event-5102878481)_.
Step 2 of _n_ pursuant to beartype/beartype#44 (where _n_ is hopefully equal to 2).
In other words, aspirationally fixes #44.

Add shiny new badge to README.rst

---

beartype_test/a90_func/doc/test_docreadme.py

The default platform encoding on Windows is the single-byte encoding cp1252.
This causes an error when reading README.rst in test_doc_readme:
`"UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1495: character maps to <undefined>"`
That is the 3rd byte in the unicode LEFT DOUBLE QUOTATION MARK character from the first code sample in the readme.

Ensure README.rst is decoded as UTF-8 in test_doc_readme on all platforms

---

README.rst

I feel ashamed to say that my original implementation of beartype validators for boto3 types was... _(gasp, shock)_ 
_incorrect_
TLDR, it appears that any kind of custom annotated type that uses just `object` as its base will not be properly validated. Thankfully I was able to find base classes in the botos that when used will ensure correct checking of custom types. And [tests](https://github.com/paulhutchings/bearboto3/blob/s3/tests/s3/test_s3.py) to prove it too! (Thank goodness for TDD or I may never have discovered this problem).

Update boto3 docs to be more accurate

---

beartype/_util/func/utilfuncmake.py
beartype_test/a00_unit/a90_decor/test_decorconf.py

Resolve #85.
Allows for debugger visibility in many contexts. (This won't work in VSCode _[by default](https://code.visualstudio.com/docs/python/debugging#_justmycode)_, but that's [on Microsoft](https://github.com/microsoft/debugpy/issues/828), not us.) @TeamSpen210 did the heavy lifting on this (see #84). I just typed it in.

Adds beartype-generated lines (no cash) to linecache

---

beartype/_util/hint/pep/utilpepget.py
beartype_test/a00_unit/a60_api/door/test_door.py
beartype_test/a00_unit/data/hint/pep/proposal/data_pep484.py

This fixes test_door for python 3.7 and 3.8 by modifying `get_hint_pep_args` to return the empty tuple if the hint is a special generic alias (i.e. has the `_special` attribute set to `True`)
see explanation for why `get_args` was involved here in https://github.com/beartype/beartype/pull/136#issuecomment-1186037251

Fix doortest for py37 py38

---

beartype/door/_doorcls.py
beartype_test/a00_unit/a60_api/door/test_door.py

support NewType, simply by checking the `__supertype__` attribute.  See comment about a future "strict" mode (that would further assert NewType identity) in the PR.

feat: add NewType Support to TypeHint

---

beartype/door/_doorcls.py
beartype_test/a00_unit/a60_api/door/test_door.py

implements https://github.com/beartype/beartype/pull/148#issuecomment-1189450220
what do you think @leycec?  is it safe to do it this way using `type(...)?`  i figured since `TypeHints` are cached, it should work?

fix: treat newtype as subtype (not an alias) of it's supertype

---

beartype/door/_doorcls.py
beartype_test/a00_unit/a60_api/door/test_door.py
tox.ini

This turned out to be easier than I thought!  Please give this a critical look (and perhaps consider any tests that you think I've overlooked).
Turns out treating TypeVar as a special case of `Union` and `Generic` as a plain old `_TypeHintSubscripted` was all that was needed to make a lot of useful test cases now pass.
I _think_ the different between `bounds` and `constraints` in TypeVars really only has meaning for static type checkers, but not so much for the sake of determining "is_subhint" compatibility.  what do you think?
This does not yet tackle covariance and contravariance

feat: Support `Generic` and `TypeVar` in `doorcls.TypeHint`

---

beartype_test/a00_unit/a60_api/door/test_door.py

adds a simple `TypeHint` smoketest for all the abcs in `typing`

add test case for all typing abcs

---

.github/workflows/python_test.yml

I noticed that the Github Actions have been failing for the last couple days:
When you click on the ones that are failing right way, they are saying:
```
Error when evaluating 'runs-on' for job 'tests'. .github/workflows/python_test.yml (Line: 171, Col: 14): Unexpected type of value '', expected type: OneOf.
```
Basically, the `include` line(s) are adding metadata to an existing matrix job (based on the key `pypy37-coverage`), but since the key is not specified in the `tox-env` list above, it creates a new, blank (!!) matrix job, hence why `${{ matrix.platform }}` is empty.

Fix CI not running

---

beartype/__init__.py

Mypy is unhappy because beartype isn't explicitly specifying its exported attributes. I assume this is a mistake since this code is not deleted but commented out.
```
error: Module "beartype" does not explicitly export attribute "beartype"; implicit reexport disabled
```

Expose beartype's `__all__`

---

.github/workflows/python_test.yml

This PR should allow this action to use mypy to validate PEP 561, without using any external actions that may not support the OSes in our matrix!
related:
https://github.com/jpetrucciani/mypy-check/issues/30
https://github.com/jpetrucciani/mypy-check/issues/31

re-add a mypy github action step, using the local python version and env

---

beartype/_util/func/utilfuncmake.py

Existing comment made this sound like a hack. This clarifies that it's a supported value intended to no-op.

[Documentation] Clarified comments on linecache module

---

doc/src/_links.rst
doc/src/faq.rst

I'd actually really recommend jaxtyping for NumPy annotations as well, but that's perhaps mildly controversial, given the existence of `nptyping`, and the official NumPy typing hints. I can do a separate PR for that if desired.

Update FAQ to recommend jaxtyping even for PyTorch

---

beartype/_conf/confcls.py
beartype/_decor/error/errormain.py

Hi @leycec 
Even if I've been silent during the last months, I have been following beartype since I'm still thinking of using it for my library. And now that you published this https://github.com/beartype/beartype/discussions/299 I had a quick reaction that resemble this:
[silence, theater lights close, Félix enters the stage]
"Oh shit. My own little dirty simili-type checker that does an okay job needs all types to be stringified, and that's why I was using `from __future__ import annotations` everywhere. Now I'm back to square one. $/%"&?|!/. Oh god, I think it's time to adopt beartype and stop thinking about it. But I still have these issues that prevent me from using it: #216 #234"
[crowd applauses]
So I decided to dive a bit and created a new configuration option …

Added is_simplified_exception configuration option.

---

beartype/_check/convert/convreduce.py
beartype/_conf/_conffrozendict.py
beartype/_conf/confcls.py

Hi @leycec
Feature #302 is done. But not.
Having a dict parameter seems to be problematic because the current code tries to build a hashable tuple of parameters (confcls.py, line 498 of this commit) but a dict is not hashable. Therefore it strongly complains.
Unfortunately I could not do much more work on it, because the whole configuration caching procedure is way out of my understanding. At least I added "stuff" so that the new config parameter now exists and it "should work". 😕
Sorry to throw this back to you!

Feature 302 done, but not.

---

beartype/__init__.py

Hi again @leycec 
The class was not available in the main beartype namespace. I added it so that I can do this code:
```python
from numbers import Integral, Real, Complex
from beartype import (
beartype,
BeartypeConf,
BeartypeViolationVerbosity,
BeartypeHintOverrides,
)
typecheck = beartype(
conf=BeartypeConf(
hint_overrides=BeartypeHintOverrides(
{int: Integral, float: Real, complex: Complex}
),
violation_param_type=TypeError,
violation_return_type=TypeError,
violation_verbosity=BeartypeViolationVerbosity.MINIMUM,
)
)
```
and use `@typecheck` everywhere I need (I prefer it to the claw at this time, it's more explicit and doesn't suffer from weird half-loaded circular input problems due to partial module reloading when I work both on my package and on beartype in a same eternal IPython …

Added the magnificent class BeartypeHintOverrides for generous use by the general user

---

README.rst

Fix typo where we are missing a closing parenthesis.

Fix Typo in README

---

beartype/_conf/confcls.py
beartype/_conf/conftest.py
beartype_test/a00_unit/a40_api/conf/test_confcls.py
tox

This is the first of two PRs for https://github.com/beartype/beartype/issues/407
It adds the plumbing for a new `claw_skip_package_names` option. A follow-up will actually implement the feature.

add plumbing for `claw_skip_package_names` option

---

doc/src/tldr.rst

Specifying `| None` is still required.
Checked that beartype actually raises an exception without it when passed `None`

Fix pep 604 optional type example

---

doc/src/faq.rst

If I use the example code without this change, I get the following errors from `mypy` and `pyright`:
```
error: Read-only property cannot override read-write property  [misc]
```
```
error: "__class__" incorrectly overrides property of same name in class "object"
  Property method "fset" is missing in override (reportIncompatibleMethodOverride)
```

Avoid static type checking error in mock types FAQ example

---

doc/src/faq.rst

Without this change, running the example gives:
```
TypeError: muh_func() missing 1 required positional argument: 'muh_arg'
```

Remove incorrect `self` argument from `mock_types` example
